/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ForLawFirmsRouteImport } from './routes/for-law-firms'
import { Route as ForContractorsRouteImport } from './routes/for-contractors'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'

const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLawFirmsRoute = ForLawFirmsRouteImport.update({
  id: '/for-law-firms',
  path: '/for-law-firms',
  getParentRoute: () => rootRouteImport,
} as any)
const ForContractorsRoute = ForContractorsRouteImport.update({
  id: '/for-contractors',
  path: '/for-contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/for-contractors': typeof ForContractorsRoute
  '/for-law-firms': typeof ForLawFirmsRoute
  '/rates': typeof RatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/for-contractors': typeof ForContractorsRoute
  '/for-law-firms': typeof ForLawFirmsRoute
  '/rates': typeof RatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/for-contractors': typeof ForContractorsRoute
  '/for-law-firms': typeof ForLawFirmsRoute
  '/rates': typeof RatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/contact'
    | '/experience'
    | '/for-contractors'
    | '/for-law-firms'
    | '/rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/contact'
    | '/experience'
    | '/for-contractors'
    | '/for-law-firms'
    | '/rates'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/contact'
    | '/experience'
    | '/for-contractors'
    | '/for-law-firms'
    | '/rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  ForContractorsRoute: typeof ForContractorsRoute
  ForLawFirmsRoute: typeof ForLawFirmsRoute
  RatesRoute: typeof RatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-law-firms': {
      id: '/for-law-firms'
      path: '/for-law-firms'
      fullPath: '/for-law-firms'
      preLoaderRoute: typeof ForLawFirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-contractors': {
      id: '/for-contractors'
      path: '/for-contractors'
      fullPath: '/for-contractors'
      preLoaderRoute: typeof ForContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  ForContractorsRoute: ForContractorsRoute,
  ForLawFirmsRoute: ForLawFirmsRoute,
  RatesRoute: RatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
